name: AudioToggle
options:
  bundleIdPrefix: com.barcartcapital
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_IDENTITY: "-"
    CODE_SIGN_STYLE: Manual

packages:
  SimplyCoreAudio:
    url: https://github.com/rnine/SimplyCoreAudio.git
    from: "4.0.0"
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts.git
    from: "2.0.0"

targets:
  AudioToggle:
    type: application
    platform: macOS
    sources:
      - path: Sources/AudioToggle
        type: group
    dependencies:
      - package: SimplyCoreAudio
      - package: KeyboardShortcuts
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.barcartcapital.AudioToggle
        INFOPLIST_FILE: Sources/AudioToggle/Info.plist
        GENERATE_INFOPLIST_FILE: false
        PRODUCT_NAME: AudioToggle
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: true
    info:
      path: Sources/AudioToggle/Info.plist
      properties:
        CFBundleName: AudioToggle
        CFBundleDisplayName: AudioToggle
        CFBundleIdentifier: com.barcartcapital.AudioToggle
        CFBundleVersion: "1"
        CFBundleShortVersionString: "1.0.0"
        CFBundlePackageType: APPL
        CFBundleExecutable: AudioToggle
        LSMinimumSystemVersion: "14.0"
        LSUIElement: true
        NSHighResolutionCapable: true
        NSUserNotificationAlertStyle: alert
